### ISSUE TITLE
Bad saturday data

### ISSUE THREAD

**Issue by paulirish** [ranmocy/rCaltrain#3]
hey @ranmocy ... does this look odd to you?
https://github.com/ranmocy/rCaltrain/blob/master/gtfs/calendar.txt#L2

seems like the data says the saturday schedule applies every day of the week.

Diff vs previous data update:

https://github.com/ranmocy/rCaltrain/commit/acc69d07c95c40566db48cdbd1675b0260866f17#diff-9f96d2aa6d66cb0e3abd11762c813088
![image](https://user-images.githubusercontent.com/39191/30342075-4ba257fa-97ad-11e7-8775-56d938354cc8.png)

I think i'm going to manually change the data.. does that seem reasonable?

cc @samccone

**Comment by paulirish** [comment]
I verified the GTFS download from http://www.caltrain.com/developer.html still has this bug. I'll email the contact there and point them to this.

**Comment by ranmocy** [comment]
I'm aware of that data. Please take a look at https://github.com/ranmocy/rCaltrain/blob/master/gtfs/calendar_dates.txt
So they remove weekday schedule as "exceptions".
And it seems like it would produce the right results as my tests, so I'm following the official data instead of manually correct it.

Let me know if you notice further odd data. Thanks!
